name: 'str' = 'temper-std'
version: 'str' = '0.0.5'
authors: 'str' = 'Temper Contributors'
description: 'str' = 'Optional support library provided with Temper'
homepage: 'str' = 'https://temperlang.dev/'
license: 'str' = 'Apache-2.0'
repository: 'str' = 'https://github.com/temper-lang/temper'
java_group: 'str' = 'dev.temperlang'
java_package: 'str' = 'temper.std'
js_name: 'str' = '@temperlang/std'
return__0: 'None' = None
export = return__0
